# Generated by Django 5.0.6 on 2024-06-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='celery_task_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='celery task id'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='provider',
            field=models.CharField(choices=[('email', 'Email'), ('web', 'Web'), ('vk', 'Vk'), ('google', 'Google'), ('telegram', 'Telegram')], max_length=128, verbose_name='provider'),
        ),
    ]
