# Generated by Django 5.0.6 on 2024-06-26 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('provider', models.CharField(choices=[('vk', 'Vk'), ('google', 'Google'), ('telegram', 'Telegram'), ('email', 'Email')], verbose_name='provider')),
                ('use_for_notifications', models.BooleanField(default=True, verbose_name='use for notifications')),
                ('social_contact', models.CharField(blank=True, max_length=256, null=True, verbose_name='social contact')),
                ('access_token', models.CharField(blank=True, max_length=256, null=True, verbose_name='access token')),
                ('refresh_token', models.CharField(blank=True, max_length=256, null=True, verbose_name='refresh token')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='extra data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SocialAccount',
                'verbose_name_plural': 'SocialAccounts',
            },
        ),
    ]
