version: '3'

services:
  api:
    build:
      context: ./api/
    image: api-image
    command: bash -c "chmod +x ./migrate_and_run.sh && bash ./migrate_and_run.sh"
    restart: unless-stopped
    container_name: api
    volumes:
      - ./api/:/src
    ports:
      - 8000:8000
    env_file:
      - ./api/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      REDIS_HOST: redis
    depends_on:
      - db
    links:
      - db

  db:
    ports:
      - 5433:5432
    image: postgres:latest
    env_file:
      - ./api/.env
    restart: unless-stopped
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis:/redis-data

  celery:
    build:
      context: ./api/
    image: api-image
    command: celery --app eventify worker -P solo
    depends_on:
      - api
      - rabbitmq
    env_file:
      - ./api/.env
    volumes:
      - ./api/:/src
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

volumes:
  redis:
    driver: local
  pgdata:
