version: '3'

services:
  api:
    build:
      context: ./api/
    image: api-image
    command: bash -c "chmod +x ./migrate_and_run.sh && bash ./migrate_and_run.sh"
    restart: unless-stopped
    container_name: api
    volumes:
      - ./api/:/src
    ports:
      - 8000:8000
    env_file:
      - ./api/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    links:
      - db

  db:
    ports:
      - 5433:5432
    image: postgres:latest
    env_file:
      - ./api/.env
    restart: unless-stopped
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
