# Generated by Django 5.0.6 on 2024-06-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_eventparticipant_anonymous_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notify_before_minutes',
            field=models.IntegerField(default=30, verbose_name='notify before minutes'),
        ),
    ]
